### ISSUE TITLE
Consider adding sync with GitHub Action from upstream project?

### ISSUE THREAD

**Issue by yihong0618** [antfu/awesome-cn-cafe-web#4]
When upstream project add new cn-coffee, this can auto generate new static website.

**Comment by antfu** [comment]
Yeah, it's indeed in the plan. I haven't got a chance to implement, so PR welcome before I work on it :)

**Comment by yihong0618** [comment]
@antfu 
Sorry I did not find a way that monitor upstream repo when it  gets a pr (in GitHub Action). 
The data not store in your repo(need to fetch),  I didnot find a good solution for GitHub Action for now maybe cron job is one way?
So wating for your solution.:) thank you ~

**Comment by antfu** [comment]
I guess a cron just to check if the upstream head changes would do. Thanks for working on this:)

**Comment by antfu** [comment]
Closing now. Thanks for your work.
